{% set version = "1.0.7" %}

package:
  name: sv-hotspot
  version: {{ version }}

source:
  git_url: https://github.com/eteleeb/SV-HotSpot.git
  git_rev: {{ version }}


build:
  number: 0
  #noarch: generic

requirements:
  build:
    #- perl >=5.10
    #- bedtools
    #- r-base ===3.3.2

  host:
    - perl >=5.10
    - perl-list-moreutils
    - bedtools ==2.29.1
    - r-base
    - r-ggplot2
    - r-peakPick
    - r-reshape2
    - r-gridExtra
    - r-plyr
    - r-gtable 
    - r-ggsignif 
    - r-RCircos
    - r-data.table

  run:
    - perl >=5.10
    - perl-list-moreutils
    - bedtools ==2.29.1
    - r-base
    - r-ggplot2
    - r-peakPick
    - r-reshape2 
    - r-gridExtra 
    - r-plyr 
    - r-gtable 
    - r-ggsignif 
    - r-RCircos
    - r-data.table

test:
    commands:
        - $R -e "library('ggplot2')"
        - sv-hotspot.pl --help

about:
  home: https://github.com/ChrisMaherLab/SV-Hotspot
  license: 'NA'
  summary: 'SV-HotSpot is a Linux-based command-line pipeline that integrates multiple 
            data types (including SVs, gene expression, and regulatory elements) to identify 
            recurrent SVs and assess their potential consequences on the gene expression of nearby genes.'

